---
- hosts: debian_hosts
  remote_user: ubuntu
  gather_facts: yes
  become: yes
  roles:
    - { debian, task_exclusions: [] }

- hosts: redhat_hosts
  remote_user: ec2-user
  become: yes
  roles:
    - redhat
