---
- hosts: debian_hosts
  remote_user: ubuntu
  gather_facts: yes
  become: yes
  roles:
    - { role: roles/debian, debian_exclusions: ['update_and_upgrade'] }

- hosts: redhat_hosts
  remote_user: ec2-user
  gather_facts: yes
  become: yes
  roles:
    - { role: roles/redhat, redhat_exclusions: [] }
