---
- hosts: debian_hosts
  remote_user: ubuntu
  gather_facts: yes
  become: yes
  roles:
    - roles/debian, debian_exclusion: [update_and_upgrade]

- hosts: redhat_hosts
  remote_user: ec2-user
  become: yes
  roles:
    - roles/redhat, redhat_exclusion: []
