---
# Playbook: Update and Upgrade the System
# Description: This playbook performs a non-interactive update and upgrade of the system.
#              The system packages are updated, and unnecessary packages are removed.
#              Finally, the system is rebooted to apply the updates.

# List of tasks directly under the playbook (no root-level "tasks" key)
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  tags: update

- name: Upgrade system packages (non-interactive)
  ansible.builtin.apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
    force_apt_get: yes
    install_recommends: yes
  environment:
    DEBIAN_FRONTEND: "noninteractive"
  tags: upgrade
  notify: Reboot the system to apply updates

- name: Re-run apt cache update after setting DEBIAN_FRONTEND
  ansible.builtin.apt:
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: "noninteractive"
  tags: upgrade
  notify: Reboot the system to apply updates

- name: Upgrade system packages again after setting DEBIAN_FRONTEND
  ansible.builtin.apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes
    force_apt_get: yes
    install_recommends: yes
  environment:
    DEBIAN_FRONTEND: "noninteractive"
  tags: upgrade
  notify: Reboot the system to apply updates
