---
# Playbook: Create MUNGE User and Group
# Description: This playbook creates the MUNGE user and group on the target hosts.
#

- name: Set MUNGEUSER variable
  ansible.builtin.set_fact:
    MUNGEUSER: 966

- name: Create MUNGE group
  ansible.builtin.group:
    name: munge
    gid: "{{ MUNGEUSER }}"
  tags: munge

- name: Create MUNGE user
  ansible.builtin.user:
    name: munge
    comment: "MUNGE Uid 'N' Gid Emporium"
    home: /var/lib/munge
    uid: "{{ MUNGEUSER }}"
    group: munge
    shell: /sbin/nologin
  tags: munge
